name: uas
description: Yu-Gi-Oh! Companion App with Card Database, Deck Builder, and Duel Tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.19.0
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true